### ISSUE TITLE
Real round-trip demo

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/simulate#15]
## Goal 

Our existing demo uses mock generation of data and shows pre-rendered videos to the user. We need a full round-trip demo.

## Acceptance criteria

- [x] Demo should use OpenFOAM damBreak simulation (see #11).
- [x] Simulator outputs are persisted to cloud storage (see #8).
- [ ] ~~Outputs listed in the JSON `outputs` field are shown to the user in the frontend.~~ (moved to https://github.com/alan-turing-institute/simulate/issues/81)

**Comment by nbarlowATI** [comment]
Richard has identified this as a first priority.

1) Better position to judge if Openfoam turnaround time is good enough.
2)

**Comment by masonlr** [comment]
Moving support for multiple outputs to https://github.com/alan-turing-institute/simulate/issues/81
